### ISSUE TITLE
No mremap on MacOS

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/pycaboose#2]
Running `example.py` on MacOS yields the following:

> Traceback (most recent call last):
>   File "./example.py", line 6, in <module>
>     a.value += 1
>   File "/Users/john/src/pycaboose/pycaboose/value.py", line 19, in value
>     self._db.write(self._key, value)
>   File "/Users/john/src/pycaboose/pycaboose/database.py", line 22, in write
>     self._writer.shrink(self._db[key].pos)
>   File "/Users/john/src/pycaboose/pycaboose/tailwriter.py", line 44, in shrink
>     self._mm.resize(tell)
> SystemError: mmap: resizing not available--no mremap()

**Comment by JohnathonNow** [comment]
Rather than memory mapping the file it might make more sense to just use file objects and call truncate.
